---
- name: Install redis
  pacman: name=redis state=present update_cache=yes

- name: Disable Transparent Huge Pages (requires reboot)
  template: src='tmpfiles_redis.conf.j2' dest='/etc/tmpfiles.d/redis.conf'

- name: Deploy sysctl config
  lineinfile: path='/etc/sysctl.d/99-sysctl.conf' line="{{ item.line }}" create=yes
  with_items:
    - { line: 'net.core.somaxconn=512' }
    - { line: 'vm.overcommit_memory=1' }
  notify:
    - reload sysctl

- meta: flush_handlers

- name: Enable and start redis daemon
  service: name=redis enabled=yes state=started