---
- name: Check if plex user exists
  getent: database=passwd key=plex fail_key=no
  when: install.plex

- name: Ensure flexget directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ flexget.config_dir }}"

- name: Pull latest FlexGet image and run docker container
  docker_container:
    name: flexget
    image: 'cpoppema/docker-flexget'
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ flexget.host_name }}"
    ports:
      - "5050:5050"
    volumes:
      - "{{ flexget.config_dir }}:/config"
    env:
      TORRENT_PLUGIN: 'transmission'
      WEB_PASSWD: "{{ flexget.web_passwd }}"
      PUID: "{% if install.plex %}{% if plex.uid != '' %}{{ plex.uid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[1] }}{% endif %}{% else %}{{ flexget.uid }}{% endif %}"
      PGID: "{% if install.plex %}{% if plex.gid != '' %}{{ plex.gid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[2] }}{% endif %}{% else %}{{ flexget.gid }}{% endif %}"

- name: Copy flexget config.yml
  template: src=config.yml dest="{{ flexget.config_dir }}"

- name: Restart flexget docker container
  docker_container:
    name: flexget
    state: started
    restart: yes