---
- name: Uninstall any existing nginx
  pacman: name=nginx state=absent
  ignore_errors: yes

- name: Install nginx-mainline
  pacman: name=nginx-mainline state=present update_cache=yes

- name: Install nginx-mainline-mod-headers-more from AUR
  kewlfft.aur.aur: name=nginx-mainline-mod-headers-more
  become: yes
  become_user: "{{ aur_user }}"
  when: nginx_install_mod_headers_more

- name: Ensure directory structure exists
  file: dest="/etc/nginx/{{ item.path }}" state=directory
  with_filetree: '../templates'
  when: item.state == 'directory'

- name: Deploy nginx configuration files
  template: src="{{ item.src }}" dest="/etc/nginx/{{ item.path }}"
  with_filetree: '../templates'
  when: item.state == 'file'
  notify:
    - restart nginx

- name: Generate DH params
  command: 'openssl dhparam -out /etc/nginx/conf.d/dhparam.pem 2048'
  args:
    creates: /etc/nginx/conf.d/dhparam.pem

- name: Generate a Self Signed OpenSSL certificate
  command: "openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/nginx/ssl/default.key -out /etc/nginx/ssl/default.crt -days 3650 -subj '/CN=localhost'"
  args:
    creates: /etc/nginx/ssl/default.crt

- name: Enable and start nginx daemon
  service: name=nginx enabled=yes state=started
