---
- name: Ensure {{ frigate_config_path | dirname }} directory exists
  ansible.builtin.file:
    path: "{{ frigate_config_path | dirname }}"
    state: directory

- name: Deploy minimal config.yml if not existing
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ frigate_config_path }}"
    force: false

- name: Pull latest Frigate image and run docker container
  community.docker.docker_container:
    name: frigate
    image: "ghcr.io/blakeblackshear/frigate:{{ frigate_version }}"
    pull: true
    recreate: true
    privileged: true
    restart_policy: 'unless-stopped'
    hostname: "{{ frigate_hostname }}"
    shm_size: "{{ frigate_shm_size }}"
    ports:
      - '5000:5000'
      - '8554:8554' # RTSP feeds
      - '8555:8555/tcp' # WebRTC over tcp
      - '8555:8555/udp' # WebRTC over udp
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - "{{ frigate_config_path }}:/config/config.yml"
      - "{{ frigate_storage_path }}:/media/frigate"
    mounts:
      - type: tmpfs
        target: /tmp/cache
        tmpfs_size: "1G"
    devices:
      /dev/bus/usb:/dev/bus/usb # passes the USB Coral
    device_requests:
      - driver: nvidia
        count: -1  # this means we want all
        capabilities:
          - ['gpu']
    env:
      FRIGATE_RTSP_USER: "{{ frigate_rtsp_username }}"
      FRIGATE_RTSP_PASSWORD: "{{ frigate_rtsp_password }}"
