#!/usr/bin/env -S ansible-playbook -e @vars.yml --vault-id @prompt
---
- hosts: all
  roles:
  - role: aur
    tags: [aur, aur-only]
    when: install.aur or install.zsh or install.vim
  - role: zsh
    tags: [zsh, aur]
    when: install.zsh
  - role: vim
    tags: [vim, aur]
    when: install.vim
  - role: tools
    tags: [tools, aur]
    when: install.tools
  - role: sshd
    become: yes
    tags: [sshd]
    when: install.sshd
  - role: syslog-ng
    become: yes
    tags: [syslog-ng]
    when: install.syslog_ng
  - role: nginx
    become: yes
    tags: [nginx]
    when: install.nginx
  - role: letsencrypt
    become: yes
    tags: [letsencrypt, letsencrypt-only]
    when: install.letsencrypt or (install.gitlab and gitlab.ssl_enabled)
  - role: nodejs
    become: yes
    tags: [nodejs]
    when: install.nodejs
  - role: redis
    become: yes
    tags: [redis]
    when: install.redis
  - role: mongodb
    become: yes
    tags: [mongodb]
    when: install.mongodb
  - role: tswbot
    become: yes
    tags: [tswbot]
    when: install.tswbot
  - role: docker
    become: yes
    tags: [docker, docker-only]
    when: install.docker or install.gitlab
  - role: gitlab
    become: yes
    tags: [gitlab, docker, letsencrypt]
    when: install.gitlab
  - role: naemon
    become: yes
    tags: [naemon, docker, letsencrypt]
    when: install.naemon
  - role: plex
    become: yes
    tags: [plex, docker, letsencrypt]
    when: install.plex
  - role: transmission
    become: yes
    tags: [transmission, transmission-only, docker]
    when: install.transmission
  - role: flexget
    become: yes
    tags: [flexget, transmission, docker]
    when: install.flexget
  - role: organizr
    become: yes
    tags: [organizr, docker, letsencrypt]
    when: install.organizr
  - role: ghost
    become: yes
    tags: [ghost, docker, letsencrypt]
    when: install.ghost
