#!/usr/bin/env -S ansible-playbook
---
- hosts: all
  roles:
  - role: arch_setup
    become: yes
    tags: [arch_setup]
    when: arch_setup
  - role: aur
    tags: [aur, aur-only]
    when: install_aur
  - role: zsh
    tags: [zsh, aur]
    when: install_zsh
  - role: vim
    tags: [vim, aur]
    when: install_vim
  - role: tools
    tags: [tools, aur]
    when: install_tools
  - role: sshd
    become: yes
    tags: [sshd]
    when: install_sshd
  - role: syslog-ng
    become: yes
    tags: [syslog-ng]
    when: install_syslog_ng
  - role: kitty
    tags: [kitty]
    when: install_kitty
  - role: nginx
    become: yes
    tags: [nginx]
    when: install_nginx
  - role: letsencrypt
    become: yes
    tags: [letsencrypt, letsencrypt-only]
    when: install_letsencrypt
  - role: nodejs
    become: yes
    tags: [nodejs]
    when: install_nodejs
  - role: redis
    become: yes
    tags: [redis]
    when: install_redis
  - role: mongodb
    become: yes
    tags: [mongodb]
    when: install_mongodb
  - role: tswbot
    become: yes
    tags: [tswbot]
    when: install_tswbot
  - role: docker
    become: yes
    tags: [docker, docker-only]
    when: install_docker
  - role: gitlab
    become: yes
    tags: [gitlab, docker, letsencrypt]
    when: install_gitlab
  - role: naemon
    become: yes
    tags: [naemon, docker, letsencrypt]
    when: install_naemon
  - role: plex
    become: yes
    tags: [plex, docker, letsencrypt]
    when: install_plex
  - role: transmission
    become: yes
    tags: [transmission, transmission-only, docker]
    when: install_transmission
  - role: flexget
    become: yes
    tags: [flexget, transmission, docker]
    when: install_flexget
  - role: organizr
    become: yes
    tags: [organizr, docker, letsencrypt]
    when: install_organizr
  - role: ghost
    become: yes
    tags: [ghost, docker, letsencrypt]
    when: install_ghost
  - role: couchdb
    become: yes
    tags: [couchdb, docker]
    when: install_couchdb
  - role: frigate
    become: yes
    tags: [frigate, docker]
    when: install_frigate
  - role: neolink
    become: yes
    tags: [neolink, docker]
    when: install_neolink
