---
- hosts: all
  become: yes
  roles:
    - { role: aur, tags: [aur, aur-only] }
    - { role: sshd, tags: [sshd] }
    - { role: zsh, tags: [zsh, aur] }
    - { role: vim, tags: [vim, aur] }
    - { role: syslog-ng, tags: [syslog-ng] }
    - { role: nginx, tags: [nginx] }
    - { role: letsencrypt, tags: [letsencrypt, letsencrypt-only] }
    - { role: nodejs, tags: [nodejs] }
    - { role: redis, tags: [redis] }
    - { role: docker, tags: [docker, docker-only] }
    - { role: gitlab, tags: [gitlab, docker, letsencrypt] }