---
- hosts: all
  become: yes
  tasks:
    - name: Include AUR
      import_role: name=aur
      tags: [aur, aur-only]
      when: install.aur or install.zsh or install.vim
    - name: Include sshd
      import_role: name=sshd
      tags: [sshd]
      when: install.sshd
    - name: Include zsh
      import_role: name=zsh
      tags: [zsh, aur]
      when: install.zsh
    - name: Include vim
      import_role: name=vim
      tags: [vim, aur]
      when: install.vim
    - name: Include syslog-ng
      import_role: name=syslog-ng
      tags: [syslog-ng]
      when: install.syslog_ng
    - name: Include nginx
      import_role: name=nginx
      tags: [nginx]
      when: install.nginx
    - name: Include letsencrypt
      import_role: name=letsencrypt
      tags: [letsencrypt, letsencrypt-only]
      when: install.letsencrypt or gitlab.ssl_enabled
    - name: Include nodejs
      import_role: name=nodejs
      tags: [nodejs]
      when: install.nodejs
    - name: Include redis
      import_role: name=redis
      tags: [redis]
      when: install.redis
    - name: Include mongodb
      import_role: name=mongodb
      tags: [mongodb]
      when: install.mongodb
    - name: Include tswbot
      import_role: name=tswbot
      tags: [tswbot]
      when: install.tswbot
    - name: Include docker
      import_role: name=docker
      tags: [docker, docker-only]
      when: install.docker or install.gitlab
    - name: Include Gitlab
      import_role: name=gitlab
      tags: [gitlab, docker, letsencrypt]
      when: install.gitlab
    - name: Include Naemon
      import_role: name=naemon
      tags: [naemon, docker, letsencrypt]
      when: install.naemon
    - name: Include Plex
      import_role: name=plex
      tags: [plex, docker, letsencrypt]
      when: install.plex
    - name: Include Transmission
      import_role: name=transmission
      tags: [transmission, transmission-only, docker]
      when: install.transmission
    - name: Include FlexGet
      import_role: name=flexget
      tags: [flexget, transmission, docker]
      when: install.flexget
