---
- hosts: all
  become: yes
  roles:
    - { role: aur, tags: [aur, aur-only] }
    - { role: sshd, tags: [sshd] }
    - { role: zsh, tags: [zsh, aur] }
    - { role: vim, tags: [vim, aur] }
    - { role: syslog-ng, tags: [syslog-ng] }