---
gitlab_config_dir: '/srv/gitlab/config'
gitlab_logs_dir: '/srv/gitlab/logs'
gitlab_data_dir: '/srv/gitlab/data'
gitlab_runner_dir: '/srv/gitlab-runner/config'
gitlab_ssh_port: '10022'
gitlab_http_port: '127.0.0.1:10080'
gitlab_https_port: '127.0.0.1:10443'
gitlab_host_name: 'gitlab'
gitlab_host: 'https://localhost'
gitlab_registry: no
gitlab_registry_host: ''
gitlab_registry_protocol: 'https'
gitlab_registry_port: '127.0.0.1:5001'
gitlab_registry_ip_auth: yes
gitlab_nginx_proxy: yes
gitlab_ssl_enabled: yes
gitlab_runner: yes
