---
- name: Ensure Naemon directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ naemon.data_dir }}"
    - "{{ naemon.logs_dir }}"
    - "{{ naemon.pnp4nagios_dir }}"

- name: Generate random thrukadmin password
  set_fact: random_pass="{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"
  when: naemon.web_admin_pass == ''

- name: Build Naemon+PNP4Nagios image
  docker_image:
    name: 'local/naemon'
    force: yes
    path: "{{ role_path }}/files"
    buildargs:
      TIME_ZONE: "{{ naemon.time_zone }}"

- name: Run Naemon docker container
  docker_container:
    name: naemon
    image: 'local/naemon'
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ naemon.host_name }}"
    ports:
      - "{{ naemon.http_port }}:80"
    volumes:
      - "{{ naemon.data_dir }}:/data"
      - "{{ naemon.pnp4nagios_dir }}:/usr/local/pnp4nagios/var"
    env:
      SMTP_HOST: "{{ naemon.smtp_host }}"
      SMTP_PORT: "{{ naemon.smtp_port }}"
      SMTP_LOGIN: "{{ naemon.smtp_user }}"
      SMTP_PASS: "{{ naemon.smtp_pass }}"
      NOTIFICATION_FROM: "{{ naemon.notification_from }}"
      WEB_ADMIN_PASSWORD: "{% if naemon.web_admin_pass != '' %}{{ naemon.web_admin_pass }}{% else %}{{ random_pass }}{% endif %}"

- name: Deploy naemon nginx vhost
  include_tasks: deploy_nginx_vhost.yml
  vars:
    host_name: "{{ naemon.host_name }}"
    http_port: "{{ naemon.http_port }}"
    logs_dir: "{{ naemon.logs_dir }}"
    ssl: "{{ naemon.ssl_enabled }}"
    server_block_beginning: |
      {% if naemon.ip_auth %}
          include snippets/ip_auth.conf;
      {% endif %}
    location_block_beginning: |+
      {% if naemon.ip_auth %}
              satisfy any;
              allow 192.168.88.0/24;
              allow 172.17.0.0/24;
              deny all;
              auth_request /auth-ip;

      {% endif %}
  when: naemon.nginx_proxy

- name: Display Thruk user and pass
  debug:
    msg:
      - 'User: thrukadmin'
      - "Pass: {% if naemon.web_admin_pass != '' %}{{ naemon.web_admin_pass }}{% else %}{{ random_pass }}{% endif %}"
