---
- name: Ensure Naemon directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ naemon.data_dir }}"
    - "{{ naemon.logs_dir }}"

- name: Generate random thrukadmin password
  set_fact: random_pass="{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"
  when: naemon.web_admin_pass == ''

- name: Pull latest Naemon image and run docker container
  docker_container:
    name: naemon
    image: 'xetusoss/naemon:latest'
    pull: yes
    state: started
    recreate: yes
    hostname: "{{ naemon.host_name }}"
    ports:
      - "{{ naemon.http_port }}:80"
    volumes:
      - "{{ naemon.data_dir }}:/data"
    env:
      SMTP_HOST: "{{ naemon.smtp_host }}"
      SMTP_PORT: "{{ naemon.smtp_port }}"
      SMTP_USER: "{{ naemon.smtp_user }}"
      SMTP_PASS: "{{ naemon.smtp_pass }}"
      WEB_ADMIN_PASSWORD: "{% if naemon.web_admin_pass != '' %}{{ naemon.web_admin_pass }}{% else %}{{ random_pass }}{% endif %}"

- name: Deploy nginx vhost config
  template: src=nginx_naemon.conf.j2 dest="/etc/nginx/vhosts.d/{{ naemon.host_name }}.conf"
  when: naemon.nginx_proxy
  notify:
    - restart nginx

- meta: flush_handlers

- name: Generate SSL cert for {{ naemon.host_name }} with letsencrypt
  command: "certbot certonly --webroot -w /var/lib/letsencrypt/ -d {{ naemon.host_name }}"
  args:
    creates: "/etc/letsencrypt/live/{{ naemon.host_name }}/fullchain.pem"
  when: naemon.nginx_proxy and naemon.ssl_enabled
  notify:
    - restart nginx

- name: Deploy nginx SSL config
  template: src=nginx_ssl.conf.j2 dest="/etc/nginx/snippets/ssl-{{ naemon.host_name }}.conf"
  when: naemon.nginx_proxy and naemon.ssl_enabled
  notify:
    - restart nginx

- name: Enable naemon SSL
  lineinfile:
    path: "/etc/nginx/vhosts.d/{{ naemon.host_name }}.conf"
    regexp: 'include snippets\/ssl'
    line: '    include snippets/ssl-{{ naemon.host_name }}.conf;'
  when: naemon.nginx_proxy and naemon.ssl_enabled
  notify:
    - restart nginx

- name: Display Thruk user and pass
  debug:
    msg:
      - 'User: thrukadmin'
      - "Pass: {% if naemon.web_admin_pass != '' %}{{ naemon.web_admin_pass }}{% else %}{{ random_pass }}{% endif %}"