---
- name: Ensure Naemon directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ naemon_data_dir }}"
    - "{{ naemon_logs_dir }}"
    - "{{ naemon_pnp4nagios_dir }}"

- name: Generate random thrukadmin password
  set_fact: random_pass="{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"
  when: naemon_web_admin_pass == ''

- name: Build Naemon+PNP4Nagios image
  docker_image:
    name: 'local/naemon'
    source: 'build'
    force_source: yes
    build:
      path: "{{ role_path }}/files"
      pull: yes
      args:
        TIME_ZONE: "{{ naemon_time_zone }}"

- name: Run Naemon docker container
  docker_container:
    name: naemon
    image: 'local/naemon'
    recreate: yes
    restart_policy: always
    hostname: "{{ naemon_host_name }}"
    ports:
      - "{{ naemon_http_port }}:80"
    volumes:
      - "{{ naemon_data_dir }}:/data"
      - "{{ naemon_pnp4nagios_dir }}:/usr/local/pnp4nagios/var"
    env:
      SMTP_HOST: "{{ naemon_smtp_host }}"
      SMTP_PORT: "{{ naemon_smtp_port }}"
      SMTP_LOGIN: "{{ naemon_smtp_user }}"
      SMTP_PASS: "{{ naemon_smtp_pass }}"
      NOTIFICATION_FROM: "{{ naemon_notification_from }}"
      WEB_ADMIN_PASSWORD: "{% if naemon_web_admin_pass != '' %}{{ naemon_web_admin_pass }}{% else %}{{ random_pass }}{% endif %}"

- name: Deploy naemon nginx vhost
  include_tasks: deploy_nginx_vhost.yml
  vars:
    host_name: "{{ naemon_host_name }}"
    http_port: "{{ naemon_http_port }}"
    logs_dir: "{{ naemon_logs_dir }}"
    ssl: "{{ naemon_ssl_enabled }}"
    server_block_beginning: |
      {% if naemon_ip_auth %}
          include snippets/ip_auth.conf;
      {% endif %}
    location_block_beginning: |+
      {% if naemon_ip_auth %}
              include snippets/ip_auth_check.conf;

      {% endif %}
  when: naemon_nginx_proxy

- name: Display Thruk user and pass
  debug:
    msg:
      - 'User: thrukadmin'
      - "Pass: {% if naemon_web_admin_pass != '' %}{{ naemon_web_admin_pass }}{% else %}{{ random_pass }}{% endif %}"
