---
- ansible.builtin.import_tasks: deploy_nginx_letsencrypt.yml
  when: ssl

- ansible.builtin.meta: flush_handlers

- ansible.builtin.import_tasks: gen_ssl_cert.yml
  when: ssl

- ansible.builtin.import_tasks: deploy_nginx_ssl.yml
  when: ssl

- ansible.builtin.import_tasks: deploy_nginx_config.yml
