---
- name: Deploy nginx vhost config {{ host_name }}.conf to sites-available
  ansible.builtin.template:
    src: nginx_vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ host_name }}.conf"
    lstrip_blocks: true
  notify:
    - restart nginx

- name: Create nginx vhost config symlink in sites-enabled
  ansible.builtin.file:
    src: "../sites-available/{{ host_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ host_name }}.conf"
    state: link
    force: true
