---
- name: Generate SSL cert for {{ host_name }} with letsencrypt
  command: "certbot certonly --webroot -w /var/lib/letsencrypt/ -d {{ host_name }}"
  args:
    creates: "/etc/letsencrypt/live/{{ host_name }}/fullchain.pem"
  notify:
    - restart nginx