---
- name: Ensure CouchDB directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ couchdb_config_dir }}"
    - "{{ couchdb_data_dir }}"

- name: Deploy obsidian.ini to {{ couchdb_config_dir }}
  copy: src=obsidian.ini dest="{{ couchdb_config_dir }}/obsidian.ini"
  when: couchdb_obsidian

- name: Pull latest CouchDB image and run docker container
  docker_container:
    name: couchdb
    image: 'couchdb'
    pull: yes
    recreate: yes
    restart_policy: always
    hostname: 'couchdb'
    ports:
      - "5984:5984"
    volumes:
      - "{{ couchdb_config_dir }}:/opt/couchdb/etc/local.d"
      - "{{ couchdb_data_dir }}:/opt/couchdb/data"
    env:
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
