---
- name: Install pacman-contrib
  community.general.pacman: name=pacman-contrib state=present update_cache=yes

- name: Enable and start paccache.timer
  ansible.builtin.service: name='paccache.timer' enabled=yes state=started

- name: Install kernel-modules-hook
  community.general.pacman: name=kernel-modules-hook state=present

- name: Install reflector
  community.general.pacman: name=reflector state=present
  when: setup_reflector

- name: Enable and start reflector.timer
  ansible.builtin.service: name='reflector.timer' enabled=yes state=started
  when: setup_reflector

- name: Ensure pacman hooks directory exists
  ansible.builtin.file: dest='/etc/pacman.d/hooks' recurse=yes state=directory
  when: setup_reflector

- name: Deploy mirrorupgrade.hook pacman hook
  ansible.builtin.copy: src=mirrorupgrade.hook dest=/etc/pacman.d/hooks/mirrorupgrade.hook
  when: setup_reflector
