---
- name: Install pacman-contrib
  pacman: name=pacman-contrib state=present update_cache=yes

- name: Install reflector
  pacman: name=reflector state=present

- name: Install kernel-modules-hook
  pacman: name=kernel-modules-hook state=present

- name: Enable and start paccache.timer
  service: name='paccache.timer' enabled=yes state=started

- name: Enable and start reflector.timer
  service: name='reflector.timer' enabled=yes state=started

- name: Ensure pacman hooks directory exists
  file: dest='/etc/pacman.d/hooks' recurse=yes state=directory

- name: Deploy mirrorupgrade.hook pacman hook
  copy: src=mirrorupgrade.hook dest=/etc/pacman.d/hooks/mirrorupgrade.hook
