---
- name: Ensure {{ aur_user }} user exists
  user: name={{ aur_user }} group=wheel
  become: yes

- name: Ensure {{ aur_user }} user has passwordless sudo access to pacman
  lineinfile:
    path: "/etc/sudoers.d/11-install-{{ aur_user }}"
    line: "{{ aur_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Install yay AUR helper
  aur: name=yay-bin
  become: yes
  become_user: "{{ aur_user }}"
