---
- name: Ensure {{ aur_user }} user exists
  user: name={{ aur_user }} group=wheel
  become: yes

- name: Install yay AUR helper with pacman
  pacman: name=yay state=present update_cache=yes
  become: yes
  register: pacman_result
  ignore_errors: yes

- name: Install yay AUR helper from AUR
  aur: name=yay-bin
  become: yes
  become_user: "{{ aur_user }}"
  when: pacman_result is failed
