---
- name: Ensure {{ aur_user }} user exists
  user: name={{ aur_user }}
  when: not aur_sudo_setup

- name: Ensure {{ aur_user }} user exists and has sudo access
  user: name={{ aur_user }} groups=wheel append=yes
  when: aur_sudo_setup

- name: Ensure {{ aur_user }} user has passwordless sudo access to pacman
  lineinfile:
    path: "/etc/sudoers.d/11-install-{{ aur_user }}"
    line: "{{ aur_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: 'visudo -cf %s'
  when: aur_sudo_setup

- name: Ensure binutils is installed
  pacman: name=binutils state=present

- name: Install paru AUR helper from AUR
  aur: name=paru-bin
  become_user: "{{ aur_user }}"
