---
- name: Check if plex user exists
  getent: database=passwd key=plex fail_key=no
  when: install_plex

- name: Ensure transmission directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ transmission_config_dir }}"
    - "{% if install_plex %}{{ plex_media_dir }}{% else %}{{ transmission_downloads_dir }}{% endif %}"
    - "{{ transmission_watch_dir }}"

- name: Pull latest Transmission image and run docker container
  docker_container:
    name: transmission
    image: 'linuxserver/transmission'
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ transmission_host_name }}"
    ports:
      - "9091:9091"
      - "51413:51413/udp"
    volumes:
      - "{{ transmission_config_dir }}:/config"
      - "{% if install_plex %}{{ plex_media_dir }}{% else %}{{ transmission_downloads_dir }}{% endif %}:/downloads"
      - "{{ transmission_watch_dir }}:/watch"
    env:
      TZ: "{{ transmission_time_zone }}"
      USER: "{{ transmission_web_user }}"
      PASS: "{{ transmission_web_passwd }}"
      WHITELIST: "{{ transmission_host_whitelist }}"
      PUID: "{% if install_plex %}{% if plex_uid != '' %}{{ plex_uid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[1] }}{% endif %}{% else %}{{ transmission_uid }}{% endif %}"
      PGID: "{% if install_plex %}{% if plex_gid != '' %}{{ plex_gid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[2] }}{% endif %}{% else %}{{ transmission_gid }}{% endif %}"

- name: Stop transmission docker container before config change
  docker_container:
    name: transmission
    state: stopped

- name: Deploy torrent done script
  template:
    src: "torrent-add.sh.j2"
    dest: "{{ transmission_config_dir }}/torrent-add.sh"
    owner: "{% if install_plex %}{% if plex_uid != '' %}{{ plex_uid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[1] }}{% endif %}{% else %}{{ transmission_uid }}{% endif %}"
    group: "{% if install_plex %}{% if plex_gid != '' %}{{ plex_gid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[2] }}{% endif %}{% else %}{{ transmission_gid }}{% endif %}"

- name: Enable torrent done script
  lineinfile:
    path: "{{ transmission_config_dir }}/settings.json"
    regexp: 'script-torrent-done-enabled'
    line: '    "script-torrent-done-enabled": true,'

- name: Remove torrent after completion
  lineinfile:
    path: "{{ transmission_config_dir }}/settings.json"
    regexp: 'script-torrent-done-filename'
    line: '    "script-torrent-done-filename": "/config/torrent-add.sh",'

- name: Download one torrent at a time
  lineinfile:
    path: "{{ transmission_config_dir }}/settings.json"
    regexp: 'download-queue-size'
    line: '    "download-queue-size": 1,'

- name: Restart transmission docker container
  docker_container:
    name: transmission
    state: started
