---
- name: Ensure Ghost directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ ghost.content_dir }}"
    - "{{ ghost.logs_dir }}"

- name: Pull latest Ghost image and run docker container
  docker_container:
    name: ghost
    image: 'ghost'
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ ghost.host_name }}"
    ports:
      - "{{ ghost.http_port }}:2368/tcp"
    volumes:
      - "{{ ghost.content_dir }}:/var/lib/ghost/content"
    env:
      url: "{{ ghost.url }}"

- name: Deploy Ghost nginx vhost
  include_tasks: deploy_nginx_vhost.yml
  vars:
    host_name: "{{ ghost.host_name }}"
    http_port: "{{ ghost.http_port }}"
    logs_dir: "{{ ghost.logs_dir }}"
    ssl: "{{ ghost.ssl_enabled }}"
  server_block_beginning: |
    {% if ghost.ip_auth %}
        include snippets/ip_auth.conf;
    {% endif %}
  location_block_beginning: |+
    {% if ghost.ip_auth %}
            satisfy any;
            allow 192.168.88.0/24;
            allow 172.17.0.0/24;
            deny all;
            auth_request /auth-ip;

    {% endif %}
  when: ghost.nginx_proxy
