---
organizr_config_dir: '/srv/organizr/config'
organizr_logs_dir: '/srv/organizr/logs'
organizr_host_name: 'organizr'
organizr_uid: ''
organizr_gid: ''
organizr_http_port: '80'
organizr_nginx_proxy: yes
organizr_ssl_enabled: yes
organizr_ip_auth: yes
