---
- name: Ensure Organizr directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ organizr_config_dir }}"
    - "{{ organizr_logs_dir }}"

- name: Pull latest Organizr image and run docker container
  docker_container:
    name: organizr
    image: 'organizr/organizr:latest'
    pull: yes
    recreate: yes
    restart_policy: always
    hostname: "{{ organizr_host_name }}"
    ports:
      - "{{ organizr_http_port }}:80"
    volumes:
      - "{{ organizr_config_dir }}:/config"
    env:
      PUID: "{{ organizr_uid }}"
      PGID: "{{ organizr_gid }}"

- name: Deploy nginx organizr auth config snippet
  template: src=nginx_organizr_auth.conf.j2 dest="/etc/nginx/snippets/organizr_auth.conf"
  when: install_nginx

- name: Deploy organizr nginx vhost
  include_tasks: deploy_nginx_vhost.yml
  vars:
    host_name: "{{ organizr_host_name }}"
    http_port: "{{ organizr_http_port }}"
    logs_dir: "{{ organizr_logs_dir }}"
    ssl: "{{ organizr_ssl_enabled }}"
    server_block_beginning: |
      {% if organizr_ip_auth %}
          include snippets/ip_auth.conf;
      {% endif %}
    location_block_beginning: |+
      {% if organizr_ip_auth %}
              include snippets/ip_auth_check.conf;

      {% endif %}
  when: organizr_nginx_proxy
