---
- name: Ensure Organizr directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ organizr.config_dir }}"
    - "{{ organizr.logs_dir }}"

- name: Pull latest Organizr image and run docker container
  docker_container:
    name: organizr
    image: 'lsiocommunity/organizr'
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ organizr.host_name }}"
    ports:
      - "{{ organizr.http_port }}:80/tcp"
    volumes:
      - "{{ organizr.config_dir }}:/config"
    env:
      PUID: "{{ organizr.uid }}"
      PGID: "{{ organizr.gid }}"

- name: Deploy nginx organizr auth config snippet
  template: src=nginx_organizr_auth.conf.j2 dest="/etc/nginx/snippets/organizr_auth.conf"
  when: install.nginx

- name: Deploy organizr nginx vhost
  include_tasks: deploy_nginx_vhost.yml
  vars:
    host_name: "{{ organizr.host_name }}"
    http_port: "{{ organizr.http_port }}"
    logs_dir: "{{ organizr.logs_dir }}"
    ssl: "{{ organizr.ssl_enabled }}"
  when: organizr.nginx_proxy
