---
- name: Generate account private key
  shell: "docker exec -i cardano jcli key generate --type=ed25519extended"
  register: ACCOUNT_SK

- name: Generate account public key
  shell: "echo {{ ACCOUNT_SK.stdout }} | docker exec -i cardano jcli key to-public"
  register: ACCOUNT_PK

- name: Generate account address
  shell: "docker exec -i cardano jcli address account {{ ACCOUNT_PK.stdout }} --testing"
  register: ACCOUNT_ADDR

- name: Save account.txt file
  lineinfile: path="{{ cardano.base_dir }}/account.txt" line="{{ item.line }}" create=yes
  with_items:
    - { line: "ACCOUNT_SK: {{ ACCOUNT_SK.stdout }}" }
    - { line: "ACCOUNT_PK: {{ ACCOUNT_PK.stdout }}" }
    - { line: "ACCOUNT_ADDR: {{ ACCOUNT_ADDR.stdout }}" }
