---
- name: Ensure directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ cardano.data_dir }}"

- name: Build jormungandr image
  docker_image:
    name: 'local/jormungandr'
    source: 'build'
    force_source: yes
    build:
      path: "{{ role_path }}/files"
      args:
        LISTEN_ADDR: "{{ cardano.listen_addr }}"
        PUBLIC_ADDR: "{{ cardano.public_addr }}"
        TIME_ZONE: "{{ cardano.time_zone }}"

- name: Run jormungandr docker container
  docker_container:
    name: cardano
    image: 'local/jormungandr'
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ cardano.host_name }}"
    ports:
      - "{{ cardano.port }}:3000"
    volumes:
      - "{{ cardano.data_dir }}:/data"
    command: "jormungandr --genesis-block-hash {{ cardano.genesis_hash }} --config /stakepool-config.yaml"
