---
- name: Install fd
  pacman: name=fd state=present update_cache=yes
  become: yes

- name: Install fuzzy finder (fzf)
  pacman: name=fzf state=present
  become: yes

- name: Install ripgrep
  pacman: name=ripgrep state=present
  become: yes

- name: Install ncdu
  pacman: name=ncdu state=present
  become: yes

- name: Install Ultimate Plumber (up) from AUR
  aur: name=up-bin
  become: yes
  become_user: "{{ aur_user }}"
