---
- name: Install htop
  community.general.pacman: name=htop state=present update_cache=yes

- name: Install procs
  community.general.pacman: name=procs state=present

- name: Install tldr
  community.general.pacman: name=tldr state=present

- name: Install lsd
  community.general.pacman: name=lsd state=present

- name: Install ripgrep (rg)
  community.general.pacman: name=ripgrep state=present

- name: Install httpie
  community.general.pacman: name=httpie state=present

- name: Install bat
  community.general.pacman: name=bat state=present

- name: Install fd
  community.general.pacman: name=fd state=present

- name: Install fuzzy finder (fzf)
  community.general.pacman: name=fzf state=present

- name: Install ncdu
  community.general.pacman: name=ncdu state=present

- name: Install dua
  community.general.pacman: name=dua-cli state=present

- name: Install broot
  community.general.pacman: name=broot state=present

- name: Install ranger
  community.general.pacman: name=ranger state=present

- name: Install sd
  community.general.pacman: name=sd state=present

- name: Install git-delta
  community.general.pacman: name=git-delta state=present

- name: Install duf
  community.general.pacman: name=duf state=present

- name: Configure git to use delta
  community.general.git_config:
    name: "{{ item.name }}"
    scope: system
    value: "{{ item.value }}"
  with_items:
    - { name: core.pager, value: delta }
    - { name: interactive.diffFilter, value: 'delta --color-only' }

- name: Configure delta style
  community.general.git_config:
    name: "{{ item.name }}"
    scope: system
    value: "{{ item.value }}"
  with_items:
    - { name: delta.navigate, value: true }
    - { name: delta.line-numbers, value: true }
    - { name: delta.side-by-side, value: true }
