---
- name: Install htop
  pacman: name=htop state=present update_cache=yes
  become: yes

- name: Install bat
  pacman: name=bat state=present
  become: yes

- name: Install fd
  pacman: name=fd state=present
  become: yes

- name: Install fuzzy finder (fzf)
  pacman: name=fzf state=present
  become: yes

- name: Install ripgrep (rg)
  pacman: name=ripgrep state=present
  become: yes

- name: Install ncdu
  pacman: name=ncdu state=present
  become: yes

- name: Install diff-so-fancy
  pacman: name=diff-so-fancy state=present
  become: yes

- name: Configure git to use diff-so-fancy
  git_config:
    name: core.pager
    scope: system
    value: 'diff-so-fancy | less --tabs=4 -RFX'
  become: yes

- name: Install Ultimate Plumber (up) from AUR
  aur: name=up-bin
  become: yes
  become_user: "{{ aur_user }}"
