---
- name: Install syslog-ng
  pacman: name=syslog-ng state=present update_cache=yes

- name: Add no_header template and log.d include to syslog-ng configuration file
  blockinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    block: |

      template no_header {
      	template("$MSG\n"); template_escape(no);
      };

      @include "log.d/*.conf"
  notify:
    - restart syslog-ng

- name: Ensure log.d dir exists
  file: path='/etc/syslog-ng/log.d' state=directory

- name: Deploy tswbot.conf
  template: src=tswbot.conf.j2 dest='/etc/syslog-ng/log.d/tswbot.conf'
  notify:
    - restart syslog-ng

- name: Enable and start syslog-ng@default daemon
  service: name=syslog-ng@default enabled=yes state=started

- name: Deploy tswbot logrotate configuration file
  template: src=tswbot.logrotate.j2 dest='/etc/logrotate.d/tswbot'