# The following lines were added by compinstall
autoload -Uz compinit
compinit
# End of lines added by compinstall

export ANTIBODY_HOME="/etc/zsh/antibody"
export ZSH="$(antibody path ohmyzsh/ohmyzsh)"
export ZSH_CUSTOM="/etc/zsh/custom"

# oh-my-zsh
DISABLE_MAGIC_FUNCTIONS=true

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

# auto-ls
AUTO_LS_COMMANDS=(/bin/lsd git-status)
AUTO_LS_NEWLINE=false

# zsh-syntax-highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# load plugins
source /etc/zsh/zsh_plugins.sh

# load theme
source "$ZSH_CUSTOM/themes/juanghurtado/juanghurtado.zsh-theme"

# set global history as default
_per-directory-history-set-global-history

# load built-in zsh zmv function
autoload -Uz zmv

[ -r /etc/zsh/zsh_aliases ] && source /etc/zsh/zsh_aliases
