---
- name: Install docker
  pacman: name=docker state=present update_cache=yes

- name: Install docker-compose
  pacman: name=docker-compose state=present

- name: Install python-docker
  pacman: name=python-docker state=present

- name: Enable and start docker daemon
  service: name=docker enabled=yes state=started
