---
- name: Install certbot
  pacman: name=certbot state=present update_cache=yes

- name: Deploy certbot.service
  template: src=certbot.service.j2 dest=/etc/systemd/system/certbot.service
  notify:
    - reload systemd

- name: Deploy certbot.timer
  template: src=certbot.timer.j2 dest=/etc/systemd/system/certbot.timer
  notify:
    - reload systemd
  meta: flush_handlers

- name: Enable and start certbot.timer
  service: name=certbot.timer enabled=yes state=started

- name: Create /var/lib/letsencrypt/.well-known for mapping ACME challenges
  file: dest='/var/lib/letsencrypt/.well-known' state=directory

- name: Set group and mode for /var/lib/letsencrypt
  file: dest=/var/lib/letsencrypt state=directory group=http mode='g+s'