---
- name: Install certbot
  pacman: name=certbot state=present update_cache=yes

- name: Deploy certbot systemd timer
  copy: src="{{ item }}" dest="/etc/systemd/system/{{ item }}"
  with_items:
    - 'certbot.service'
    - 'certbot.timer'
  notify:
    - reload systemd

- meta: flush_handlers

- name: Enable and start certbot.timer
  service: name=certbot.timer enabled=yes state=started

- name: Create /var/lib/letsencrypt/.well-known for mapping ACME challenges
  file: dest='/var/lib/letsencrypt/.well-known' state=directory

- name: Set group and mode for /var/lib/letsencrypt
  file: dest=/var/lib/letsencrypt state=directory group=http mode='g+s'

- name: Ensure nginx snippets dir exists
  file: dest=/etc/nginx/snippets state=directory
  when: install.nginx

- name: Deploy nginx letsencrypt config
  template: src=letsencrypt.conf.j2 dest=/etc/nginx/snippets/letsencrypt.conf
  when: install.nginx