---
- name: Check if plex user exists
  getent: database=passwd key=plex fail_key=no

- name: Create plex user
  user: name=plex shell=/sbin/nologin
  when: not getent_passwd.plex and plex.media_dir | search('/home/plex')

- name: Ensure plex directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ plex.config_dir }}"
    - "{{ plex.transcode_dir }}"
    - "{{ plex.media_dir }}"
    - "{{ plex.logs_dir }}"

- name: Pull latest Plex Media Server image and run docker container
  docker_container:
    name: plex
    image: 'plexinc/pms-docker:public'
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    hostname: "{{ plex.host_name }}"
    exposed_ports:
      - "{% if plex.webtools %}33400:33400/tcp{% endif %}"
      - "{% if plex.webtools %}33443:33443/tcp{% endif %}"
    published_ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "{% if plex.webtools %}33400:33400/tcp{% endif %}"
      - "{% if plex.webtools %}33443:33443/tcp{% endif %}"
    volumes:
      - "{{ plex.config_dir }}:/config"
      - "{{ plex.transcode_dir }}:/transcode"
      - "{{ plex.media_dir }}:/data"
    env:
      TZ: "{{ plex.time_zone }}"
      ADVERTISE_IP: "{{ plex.advertise_ip }}"
      PLEX_UID: "{% if plex.uid != '' %}{{ plex.uid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[1] }}{% endif %}"
      PLEX_GID: "{% if plex.gid != '' %}{{ plex.gid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[2] }}{% endif %}"

- name: Ensure Plex plugins directory structure exists
  file: dest="{{ plex.config_dir }}/Library/Application Support/Plex Media Server/Plug-ins" recurse=yes state=directory
  when: plex.webtools

- name: Download latest WebTools plug-in
  shell: "curl -s https://api.github.com/repos/ukdtom/WebTools.bundle/releases/latest | grep browser_download_url | cut -d \" -f 4 | wget -qi -"
  when: plex.webtools

- name: Unzip WebTools plug-in and remove zip
  shell: "unzip WebTools.bundle.zip && rm WebTools.bundle.zip"
  when: plex.webtools

- name: Install WebTools plug-in
  shell: "mv WebTools.bundle {{ plex.config_dir }}/Library/Application Support/Plex Media Server/Plug-ins/"
  when: plex.webtools

- name: Change WebTools folder owner and group
  file:
    dest: "{{ plex.config_dir }}/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle"
    recurse: yes
    owner: "{% if plex.uid != '' %}{{ plex.uid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[1] }}{% endif %}"
    group: "{% if plex.gid != '' %}{{ plex.gid }}{% elif getent_passwd.plex %}{{ getent_passwd.plex[2] }}{% endif %}"
  when: plex.webtools

- name: Deploy nginx vhost config
  template: src=nginx_plex.conf.j2 dest="/etc/nginx/vhosts.d/{{ plex.host_name }}.conf"
  when: plex.nginx_proxy
  notify:
    - restart nginx

- meta: flush_handlers

- name: Generate SSL cert for {{ plex.host_name }} with letsencrypt
  command: "certbot certonly --webroot -w /var/lib/letsencrypt/ -d {{ plex.host_name }}"
  args:
    creates: "/etc/letsencrypt/live/{{ plex.host_name }}/fullchain.pem"
  when: plex.nginx_proxy and plex.ssl_enabled
  notify:
    - restart nginx

- name: Deploy nginx SSL config
  template: src=nginx_ssl.conf.j2 dest="/etc/nginx/snippets/ssl-{{ plex.host_name }}.conf"
  when: plex.nginx_proxy and plex.ssl_enabled
  notify:
    - restart nginx

- name: Enable plex SSL
  lineinfile:
    path: "/etc/nginx/vhosts.d/{{ plex.host_name }}.conf"
    regexp: 'include snippets\/ssl'
    line: '    include snippets/ssl-{{ plex.host_name }}.conf;'
  when: plex.nginx_proxy and plex.ssl_enabled
  notify:
    - restart nginx

- name: Deploy plex update systemd timer
  copy: src="{{ item }}" dest="/etc/systemd/system/{{ item }}"
  with_items:
    - 'plex-update.service'
    - 'plex-update.timer'
  notify:
    - reload systemd

- meta: flush_handlers

- name: Enable and start plex-update.timer
  service: name='plex-update.timer' enabled=yes state=started