---
- name: Ensure plex directory structure exists
  file: dest="{{ item }}" recurse=yes state=directory
  with_items:
    - "{{ plex.config_dir }}"
    - "{{ plex.transcode_dir }}"
    - "{{ plex.media_dir }}"

- name: Pull latest Plex Media Server image and run docker container
  docker_container:
    name: plex
    image: 'plexinc/pms-docker:public'
    pull: yes
    state: started
    recreate: yes
    hostname: "{{ plex.host_name }}"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - "{{ plex.config_dir }}:/config"
      - "{{ plex.transcode_dir }}:/transcode"
      - "{{ plex.media_dir }}:/data"
    env:
      TZ: "{{ plex.time_zone }}"
      ADVERTISE_IP: "{{ plex.advertise_ip }}"
      PLEX_UID: "{{ plex.uid }}"
      PLEX_GID: "{{ plex.gid }}"