---
- name: Ensure Tautulli directory exists
  file: dest="{{ plex_tautulli_config_dir }}" recurse=yes state=directory

- name: Pull latest Tautulli image and run docker container
  docker_container:
    name: tautulli
    image: 'tautulli/tautulli'
    pull: yes
    recreate: yes
    restart_policy: always
    hostname: 'tautulli'
    ports:
      - "8181:8181"
    volumes:
      - "{{ plex_tautulli_config_dir }}:/config"
      - "{{ plex_config_dir }}/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    env:
      TZ: "{{ plex_time_zone }}"
      PUID: '0'
      PGID: '0'
