---
- name: Ensure Tautulli directory exists
  file: dest="{{ plex.tautulli_config_dir }}" recurse=yes state=directory

- name: Pull latest Tautulli image and run docker container
  docker_container:
    name: tautulli
    image: 'tautulli/tautulli'
    pull: yes
    state: started
    recreate: yes
    restart_policy: always
    hostname: 'tautulli'
    ports:
      - "8181:443/tcp"
    volumes:
      - "{{ plex.tautulli_config_dir }}:/config"
      - "{{ plex.config_dir }}/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    env:
      TZ: "{{ plex.time_zone }}"
      PUID: 0
      PGID: 0
