---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Configure OpenSSH daemon configuration file
  lineinfile: path=/etc/ssh/sshd_config line="{{ item.line }}"
  with_items:
    - { line: 'X11Forwarding yes' }
    - { line: 'PermitRootLogin yes' }
    - { line: 'AllowUsers root' }
  notify:
    - sshd restart

- name: Enable and start OpenSSH daemon
  service: name=sshd enabled=yes state=started